export enum ERoomState {
  NOT_STARTED = 'NOT_STARTED',
  STARTED = 'STARTED',
  STARTED_NOT_AVAILABLE = 'STARTED_NOT_AVAILABLE',
  STARTED_AVAILABLE = 'STARTED_AVAILABLE',
  STOPPED = 'STOPPED',
  FAILED = 'FAILED'
}
